export const listItems = [
    {
      id:"Todo",
      title:"To Do",
      color:"#FA9189",
      tasks:[
        {
            id:'t14',
            name:'task1'
        }
      ]
    },    
    {
      id:"InProgress",
      title:"In Progress",
      color:"#FFE699",
      tasks:[
        {
            id:'t13',
            name:'task1'
        }
      ]
    },    
    {
      id:"OnApproval",
      title:"On Approval",
      color:"#C1C9E8",
      tasks:[
        {
            id:'t1',
            name:'task1'
        },
        {
            id:'t2',
            name:'task2'
        },
        {
            id:'t3',
            name:'task3'
        }
      ]
    },    
    {
      id:"Done",
      title:"Done",
      color:"#B3F5BC",
      tasks:[
        {
            id:'t11',
            name:'task1'
        }
      ]
    }
  ];